[package]
name = "terrain-destruction"
version = "1.0.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = {version = "4.5.32", features = ["derive"] }
ggez = "0.9.3"
lazy_static = "1.5.0"
noise = "0.9.0"
rand = "0.9.0"
rayon = "1.10.0"
rodio = "0.20.1"

[profile.dev]
opt-level = 3

